### ISSUE TITLE
Code import not available?

### ISSUE THREAD

**Issue by DanPigment** [aimeos/ai-cms-grapesjs#12]
Hi.
I've overridden the custom.js to activate some panels
I especially want to use the export and import-html, but when it's activated using 
`
Aimeos.CMSContent.GrapesJS.panels = [{
      id: 'impexp',
      buttons: [{
        id: 'export-template',
        className: 'fa fa-code',
        command: e => e.runCommand('export-template'),
      },{
        id: 'gjs-open-import-webpage',
        className: 'fa fa-upload',
        command: e => e.runCommand('gjs-open-import-webpage'),
      }]
`
I get the buttons, export opens a panel with html & css, import gives the console error
'gjs-open-import-webpage' command not found'

Is this not supported?

**Comment by aimeos** [comment]
Maybe this requires a GrapesJS plugin
