### ISSUE TITLE
GrapeJS - open style manager bug

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-cms-grapesjs#17]
I think I found an error in the GrapeJS component.

After turning on "Open style manager" and "Open layer manager".
![image](https://user-images.githubusercontent.com/61547701/154793716-332ca2bc-5e4d-4d8d-8f7e-18f18f124b77.png)

When I click on the "Open style manager" button, a "Device" drop-down will appear in the upper right corner.
![image](https://user-images.githubusercontent.com/61547701/154793737-da562918-3d8f-4d14-82d0-442f931c7bd6.png)

I don't think it needs to be here.
In the upper left corner is the screen selector.
![image](https://user-images.githubusercontent.com/61547701/154793801-1a2d8268-c283-45b0-bb96-da3a80162253.png)

The height of the entire menu bar will change when it appears.
![image](https://user-images.githubusercontent.com/61547701/154793818-f457f10f-692f-45af-98a1-7a5b4d28d8c3.png)

This quick fix solves the problem, but I think there is a nicer solution as well:
`.gjs-pn-devices-c {
    display: none;
}`

**Comment by aimeos** [comment]
Can you create a PR for the required CSS?
