### ISSUE TITLE
GrapeJS - Open Style Manager does not work

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-cms-grapesjs#18]
Hello!

1. I created a blank page in the CMS and saved it

2. I put "2 cols" in the editor and saved it
![image](https://user-images.githubusercontent.com/61547701/154794809-ab555624-95e8-4944-a291-dd7f6c73e8b6.png)

3. I saw this on the frontend, everything is fine
![image](https://user-images.githubusercontent.com/61547701/154794866-b830c18e-e576-4b07-a203-33a75ade129f.png)

4. I selected the DIV on the right and opened the "Open Style Manager"
![image](https://user-images.githubusercontent.com/61547701/154794926-a4eaf71e-a46d-4a2e-92a6-2e440048c16b.png)
**This is an error because it does not show that the item has a "col" class.**
**Anything I can change will be lost.**

5. I clicked on the body element, clicked back to the DIV on the right and opened the "Open Style Manager" again.
It finally shows the "col" class and the "Dimension" section is not empty either.
![image](https://user-images.githubusercontent.com/61547701/154795802-b6f520cd-2912-487a-b719-51d8ec24e4b0.png)

6. I typed 500 into the height input.
I clicked on the body element, clicked back to the DIV on the right and opened the "Open Style Manager" again.
![image](https://user-images.githubusercontent.com/61547701/154795909-80f636c6-cfd2-4a85-8524-90738b53f389.png)

7. I saved it. 
**I don't see any settings on the frontend.
I don't see "height" or "min-height" in CSS.**
![image](https://user-images.githubusercontent.com/61547701/154795997-72467b01-c0e5-44c7-9aae-db2a01304a63.png)
![image](https://user-images.githubusercontent.com/61547701/154796082-512037f4-a9e1-480b-adb7-f886efe292e8.png)
![image](https://user-images.githubusercontent.com/61547701/154796092-e284f8e6-667c-4d76-8925-4be48e8583ac.png)

8. **In the "margin" section, all letters and buttons are white and the background is white.**
![image](https://user-images.githubusercontent.com/61547701/154796113-d09cfbc6-65b0-48db-b48c-8cb2413328e7.png)
![image](https://user-images.githubusercontent.com/61547701/154796143-b941d3d0-1cba-4997-99f1-a38aeab361d9.png)

**Anything I can change, nothing appears on the frontend.**

It wouldn’t be such a big deal if I could add a class to the items, but it doesn’t work.
Can you help me in this?
Am I doing something wrong?
Or is this part not yet developed?
The weird thing is that the admin saves the settings, I just don't see it on the frontend.

**Comment by aimeos** [comment]
We don't store and add any custom CSS in the frontend, mainly due to layout and security reasons.

The "col" class is only missing in the style manager when you click on the element the first time. If you click again on the element, the class does show up in the style manager. This might be a bug either in GrapesJS or there's something missing in the "cols" component:
https://github.com/aimeos/ai-cms-grapesjs/blob/master/admin/jqadm/themes/custom.js#L449-L516

The main problem with adding new classes is that you have to hit the "Enter" button to add the new class but this also submits the Aimeos form without adding the CSS class first. Can you have a look how we can prevent the form submit?

**Comment by Ameeko** [comment]
If the form in the admin can get an "admin-form" id (the "logout-form" has)
Then this code solves the problem:

```
document.getElementById("admin-form").addEventListener("submit", function(event) {
     if(document.activeElement === document.getElementById("gjs-clm-new")){
         event.preventDefault();
     } 
}, true);
```

If it can't get an id, I can target the second form based on the tag name:

```
document.getElementsByTagName("form")[1].addEventListener("submit", function(event) {
    if(document.activeElement === document.getElementById("gjs-clm-new")){
        console.log('sss');
        event.preventDefault();
    } 
}, true);
```

I don't really know what the rules are, can I use JQuery or not.

I don't even know where to put it. 
I put it here in my project and it works fine:
/ext/myext/admin/jqadmin/js/custom.js

Maybe this would be the best place for it:
/vendor/aimeos/ai-cms-grapejs/admin/jqadmin/themes/custom.js

I don't know if it's worth using in the master, this bugfix is enough for me.

**Comment by aimeos** [comment]
It would be great if you could open an issue in the GrapesJS repo as this must be fixed there:
https://github.com/artf/grapesjs

**Comment by Ameeko** [comment]
I did it.
I think that can be closed.
https://github.com/artf/grapesjs/issues/4166
