### ISSUE TITLE
Full GrapeJS code in every admin page + CKEditor

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-cms-grapesjs#20]
Each admin page induces ckeditor.js
`<script src = "https://cdn.jsdelivr.net/npm/ckeditor@4/ckeditor.js"> </script>`
Is this necessary?

Each admin page puts the full GrapeJS code into this JS:
`/admin/default/jqadm/file/js`
I think this is unnecessary, it would be enough to just pull it into the CMS page

**Comment by Ameeko** [comment]
and the ckeditor?
is it used somewhere in the system?

**Comment by aimeos** [comment]
Yes, in all "Text" sub-panels.

**Comment by Ameeko** [comment]
You're right.
I understood.
Thanks.
