### ISSUE TITLE
Link block element problems

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-cms-grapesjs#22]
Hello!

If I create a **Link block** element in GrapesJS, I can put a **Container** or **Header** or **Paragraph** element in it.
If I create a **Link block** element and then press the save button, then nothing can be dragged into the **Link block** element.

I think this is not a GrapesJS bug, but something happens when Aimeos saves the data.
The grapesjs.com demo page works fine (but there is no save button on that page).

Maybe the problem is that after saving, GrapesJS thinks this element is a normal **Link** and not **Link block**.
(No element can be inserted into a normal **Link** element in GrapesJS.)

...but I don’t know how these two elements are different in HTML.

**Comment by aimeos** [comment]
The problem has been fixed and the fix is available when installing:
```
composer req aimeos/ai-cms-grapesjs:2021.10.x-dev
```

**Comment by Ameeko** [comment]
It works.
Thank you very much.
