### ISSUE TITLE
The "2 cols" element cannot be inserted in the "background" element

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-cms-grapesjs#23]
Hello!
The "2 cols" element cannot be inserted in the "background" element.
Is there a reason for this?
The background element is a plain DIV, anything should be put into it.
If I put a container in the "Background" element, I can then put the "2 cols" element in it.

**Comment by aimeos** [comment]
It's now possible if you install:
```
composer req aimeos/ai-cms-grapesjs:2021.10.x-dev
```

**Comment by Ameeko** [comment]
It works after the update.
Thank you very much!
