### ISSUE TITLE
Cannot delete CMS pages

### ISSUE THREAD

**Issue by defive** [aimeos/ai-cms-grapesjs#24]
Currently I cannot delete CMS pages on either the default site or any sub-sites that have been created.

Using the trash icon or the tickbox, then selecting delete both result in an error in the Javascript console as follows and the page is not deleted:

```
TypeError: ev is undefined
    askDelete js:5431
    VueJS 2
        click
        fn
[vue.min.js:11](https://cdn.jsdelivr.net/npm/vue@2.7.8/dist/vue.min.js)
    VueJS 33
    init js:5361
    <anonymous> js:5803
    jQuery 13
```

Version is 2022.07.02

**Comment by aimeos** [comment]
Can you try this please?
```
composer req aimeos/ai-cms-grapesjs:2022.07.x-dev
```
The problem should be fixed there.

**Comment by defive** [comment]
Perfect, yes that update has fixed the issue. Thank you.
