### ISSUE TITLE
cms is not working for multi sites

### ISSUE THREAD

**Issue by mukulviru** [aimeos/ai-cms-grapesjs#25]
for multi sites cms is not working

**Comment by aimeos** [comment]
Can you please be much more specific?
We need a detailed bug report to be able to care about issues.

**Comment by mukulviru** [comment]
please check for multisite cms is not showing ....i have checked ....it is working in "aimeos/aimeos-laravel": "2022.07.4"
[https://aimeos.org/help/download/file.php?id=1356](url)

**Comment by aimeos** [comment]
See https://aimeos.org/help/viewtopic.php?f=18&t=4812
