### ISSUE TITLE
Cannot save media

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-cms-grapesjs#26]
I'm trying to create page with media with filled option (option: type, value: example) in "advanced" section, but an error appears:

Aimeos\MShop\Common\Item\Lists\Standard::setPosition(): Argument #1 ($pos) must be of type int, string given, called in /var/www/vendor/aimeos/ai-cms-grapesjs/src/Admin/JQAdm/Cms/Media/Standard.php on line 373

PHP 8.1.12
Laravel 9.40.1

**Comment by aimeos** [comment]
Can't reproduce that issue but there was a JS error when you add a second list type for media.
Can you please install the new version and tell us if it works now:
```
composer req aimeos/ai-cms-grapesjs:2022.10.x-dev
```

**Comment by Tantacula** [comment]
> Can't reproduce that issue but there was a JS error when you add a second list type for media. Can you please install the new version and tell us if it works now:
> 
> ```
> composer req aimeos/ai-cms-grapesjs:2022.10.x-dev
> ```

the problem still here, media with options causes error during page saving

**Comment by aimeos** [comment]
Can you add a `var_dump( $idx )` before this line and post the output (should be "string ..."):
https://github.com/aimeos/ai-cms-grapesjs/blob/master/src/Admin/JQAdm/Cms/Media/Standard.php#L373

**Comment by Tantacula** [comment]
I found that input names in admin panel like "media[_idx_][config][0][key]" and "media[_idx_][config][0][val]" should be replaced by "media[0]" for correct working

**Comment by aimeos** [comment]
Thanks, that helped!
We've fixed the problem, can you execute this command and test again?
```
composer req aimeos/ai-cms-grapesjs:2022.10.x-dev
```

**Comment by Tantacula** [comment]
Problem is solved now, thank you)
