### ISSUE TITLE
Cannot add images to CMS pages

### ISSUE THREAD

**Issue by defive** [aimeos/ai-cms-grapesjs#28]
I cannot add or edit images on CMS pages. Adding an image block or double-clicking an existing block opens a blank window as below.

There are no errors in the browser console.

![Screenshot from 2022-12-13 09-29-24](https://user-images.githubusercontent.com/13240380/207280876-89c19d75-379c-45ad-bcfc-b720e225b682.png)

**Comment by aimeos** [comment]
You must upload an image in the "Media" tab first.

**Comment by defive** [comment]
Ah! Yes it works, thanks
