### ISSUE TITLE
Columns in Grape Editor are hard to manipulate

### ISSUE THREAD

**Issue by Dahercode** [aimeos/ai-cms-grapesjs#7]
Hello Aimeos, I added grapejs to my aimeos project (Laravel), and i figured that the editor in the content section (JQADM) has a small issue : After inserting the columns, it's really hard to insert text or any content inside. 

Is it a general issue ? 

Thank you

**Comment by aimeos** [comment]
That depends on what you think the problem is. If the column is too small, you could add more padding or add a minimum height for columns:
https://github.com/aimeos/ai-cms-grapesjs/blob/master/admin/jqadm/themes/custom.js#L418

**Comment by Dahercode** [comment]
> That depends on what you think the problem is. If the column is too small, you could add more padding or add a minimum height for columns:
> https://github.com/aimeos/ai-cms-grapesjs/blob/master/admin/jqadm/themes/custom.js#L418

Thank you, it solves my issue. I think it's better to put a bigger padding by default, the 10 px value is nearly impossible to work with (I may be wrong^^)

**Comment by aimeos** [comment]
A padding has the problem that is may interfere too much with the design of the frontend. Is this change is enough for you?
```
.gjs-dashed .row, .gjs-dashed .col, .gjs-dashed [class^="col-"] {
	min-height: 3rem !important;
}
```

**Comment by aimeos** [comment]
If you need more space between the row and the columns, we should use the padding instead. Is it enough to increase the row padding from 10px to 20px?

**Comment by Dahercode** [comment]
Indeed, i think it's enough, but, it still has a weird behaviour compared to adding "min-height". 
I recorded quikcly the impact (Orginal code / Increasing padding / Adding a min-height)

- [Original code (actual)](https://ibb.co/qJF23sq)
- [Increasing padding by 10px](https://ibb.co/hZ6Jvgn)
- [Adding min-height](https://ibb.co/0GCwqv6)

**Comment by aimeos** [comment]
Your screenshots always shows the same image so we can't see what you mean

**Comment by Dahercode** [comment]
It's a .gif (animated screenshots), you just have to wait some seconds to charge :D

**Comment by aimeos** [comment]
OK, can you create a pull request with the necessary changes?

**Comment by Dahercode** [comment]
Sure, can you first choose beetween the last 2 behaviours ? ( With padding or min-height )

**Comment by aimeos** [comment]
Think, the min-height way would be preferrable

**Comment by Dahercode** [comment]
Done : https://github.com/aimeos/ai-cms-grapesjs/pull/8
